defaultEntryPoints = ["http", "https"]

[entryPoints]
	[entryPoints.http]
	address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
	[entryPoints.https]
	address = ":443"
		[entryPoints.https.tls]

[api]
dashboard = false

[acme]
email = "contact@nicolasdubouilh.fr"
storage = "acme.json"
onHostRule = true
entryPoint = "https"
	[acme.dnsChallenge]
	provider = "ovh"
	delayBeforeCheck = 0

[docker]
	endpoint = "unix:///var/run/docker.sock"
	exposedByDefault = false
